import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { access, mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { initializeProjectMemory } from '../init.js';
import { scanProjectMemory } from '../project-memory.js';
import { sha256Text } from '../hash.js';
import { fileURLToPath } from 'node:url';
import { parseCliArgs, runCli, isDirectExecution } from '../cli.js';

test('initializeProjectMemory scaffolds a new root and writes a manifest', async () => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'vibecompass-init-'));
  const rootDir = path.join(tempDir, '.compass');

  try {
    const result = await initializeProjectMemory({
      rootDir,
      name: 'Example Project',
      slug: 'example-project',
      mode: 'local-only',
      repos: [
        {
          id: 'docs',
          remote: 'https://github.com/example/docs.git',
          defaultBranch: 'main',
        },
      ],
      generatedAt: new Date('2026-04-19T10:00:00Z'),
    });

    const projectYaml = await readFile(path.join(rootDir, 'project.yaml'), 'utf8');
    const gitignore = await readFile(path.join(rootDir, '.gitignore'), 'utf8');
    const starterArchitecture = await readFile(path.join(rootDir, 'architecture/overview/project-shape.md'), 'utf8');
    const decisionExample = await readFile(path.join(rootDir, 'decisions/EXAMPLE.md'), 'utf8');
    const starterSession = await readFile(path.join(rootDir, 'sessions/2026-04-19-1-project-memory-initialized.md'), 'utf8');
    const manifest = JSON.parse(await readFile(result.manifestPath, 'utf8'));

    assert.match(projectYaml, /name: Example Project/);
    assert.match(projectYaml, /slug: example-project/);
    assert.match(projectYaml, /default_branch: main/);
    assert.match(projectYaml, /reviewer_handback: handoff-file/);
    assert.match(projectYaml, /refresh_architecture_docs: true/);
    assert.match(projectYaml, /refresh_decision_files: true/);
    assert.match(projectYaml, /commit_template: "docs\(session\): YYYY-MM-DD-N — <summary>"/);
    assert.equal(gitignore, 'state/\n');
    assert.match(starterArchitecture, /confidence: Initial scaffold/);
    assert.match(starterArchitecture, /repos:\n  - "docs"/);
    assert.match(starterArchitecture, /## Coverage/);
    assert.match(decisionExample, /example-only guidance/);
    assert.match(starterSession, /# Session — 2026-04-19-1 — Project Memory Initialized/);
    assert.match(starterSession, /Generated by `vibecompass init`/);
    assert.equal(manifest.generated_at, '2026-04-19T10:00:00.000Z');
    assert.equal(manifest.canonical.document_count, 3);
    assert.deepEqual(Object.keys(manifest.documents), [
      'architecture/overview/project-shape.md',
      'project.yaml',
      'sessions/2026-04-19-1-project-memory-initialized.md',
    ]);
    assert.equal(result.contextFilePath, null);
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});

test('initializeProjectMemory can scaffold workflow guides and starter tool files', async () => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'vibecompass-init-bootstrap-'));
  const rootDir = path.join(tempDir, '.compass');

  try {
    const result = await initializeProjectMemory({
      cwd: tempDir,
      rootDir,
      name: 'Workflow Project',
      mode: 'local-only',
      repos: [{ id: 'docs', remote: 'https://github.com/example/docs.git' }],
      closeSessionGitPublish: true,
      closeSessionGitRemote: 'origin',
      generatedAt: new Date('2026-04-20T08:00:00Z'),
      bootstrap: {
        workflow: true,
        claude: true,
        agents: true,
      },
    });

    const context = await readFile(path.join(rootDir, 'context.md'), 'utf8');
    const architectureGuide = await readFile(path.join(rootDir, 'architecture/README.md'), 'utf8');
    const decisionsGuide = await readFile(path.join(rootDir, 'decisions/README.md'), 'utf8');
    const sessionsGuide = await readFile(path.join(rootDir, 'sessions/README.md'), 'utf8');
    const starterArchitecture = await readFile(path.join(rootDir, 'architecture/overview/project-shape.md'), 'utf8');
    const decisionExample = await readFile(path.join(rootDir, 'decisions/EXAMPLE.md'), 'utf8');
    const starterSession = await readFile(path.join(rootDir, 'sessions/2026-04-20-1-project-memory-initialized.md'), 'utf8');
    const claude = await readFile(path.join(tempDir, 'CLAUDE.md'), 'utf8');
    const agents = await readFile(path.join(tempDir, 'AGENTS.md'), 'utf8');

    assert.match(context, /\.compass\/project\.yaml/);
    assert.match(context, /active builder sessions are named lanes/);
    assert.match(context, /Entry trigger/);
    assert.match(context, /Optional planning mode/);
    assert.match(context, /`close session` — builder runs the close-out checklist/);
    assert.match(context, /end-session` is also accepted as an alias/);
    assert.match(context, /reports stale scratch files/);
    assert.match(context, /Documentation coverage/);
    assert.match(context, /vibecompass docs-review --guided/);
    assert.match(context, /sessions\/active\/<lane-id>\/wip\.md/);
    assert.match(context, /include a Git publish step after finalization using remote `origin`/);
    assert.match(context, /use commit message format `docs\(session\): YYYY-MM-DD-N — <summary>`/);
    assert.match(architectureGuide, /Recommended layout/);
    assert.match(architectureGuide, /`repos`: array of repo IDs/);
    assert.match(decisionsGuide, /Append-only decision log/);
    assert.match(sessionsGuide, /Finalized session notes/);
    assert.match(starterArchitecture, /Initial project-memory scaffold/);
    assert.match(decisionExample, /ignored by VibeCompass canonical decision parsing/);
    assert.match(starterSession, /Project Memory Initialized/);
    assert.match(claude, /Read `\.compass\/context\.md` before doing substantive work/);
    assert.match(claude, /Entry trigger/);
    assert.match(claude, /planning mode/);
    assert.match(claude, /`close session` — builder runs the close-out checklist/);
    assert.match(claude, /end-session` is accepted as an alias/);
    assert.match(claude, /stale scratch files block `start-session`/);
    assert.match(agents, /Before doing substantive work/);
    assert.match(agents, /Entry trigger/);
    assert.match(agents, /planning mode/);
    assert.match(agents, /`close session` — builder runs the close-out checklist/);
    assert.match(agents, /end-session` is accepted as an alias/);
    assert.equal(result.contextFilePath, path.join(rootDir, 'context.md'));
    assert.ok(result.scaffoldCreatedFiles.includes(path.join(tempDir, 'CLAUDE.md')));
    assert.ok(result.scaffoldCreatedFiles.includes(path.join(tempDir, 'AGENTS.md')));
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});

test('initializeProjectMemory supports dedicated-memory-repo placement defaults', async () => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'vibecompass-init-dedicated-root-'));
  const docsRepoDir = path.join(tempDir, 'vibecompass-docs');

  try {
    await mkdir(docsRepoDir, { recursive: true });

    const result = await initializeProjectMemory({
      cwd: tempDir,
      toolingRootDir: 'vibecompass-docs',
      placementPattern: 'dedicated-memory-repo',
      name: 'Dedicated Memory Project',
      mode: 'local-only',
      repos: [{ id: 'docs', remote: 'https://github.com/example/docs.git' }],
      bootstrap: {
        workflow: true,
        claude: true,
      },
    });

    const projectYaml = await readFile(path.join(docsRepoDir, 'project.yaml'), 'utf8');
    const context = await readFile(path.join(docsRepoDir, 'context.md'), 'utf8');
    const claude = await readFile(path.join(docsRepoDir, 'CLAUDE.md'), 'utf8');

    assert.equal(result.rootDir, docsRepoDir);
    assert.equal(result.contextFilePath, path.join(docsRepoDir, 'context.md'));
    assert.match(projectYaml, /placement_pattern: dedicated-memory-repo/);
    assert.match(context, /project\.yaml/);
    assert.match(claude, /Read `context\.md` before doing substantive work/);
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});

test('initializeProjectMemory supports workspace-root placement defaults', async () => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'vibecompass-init-workspace-root-'));
  const workspaceDir = path.join(tempDir, 'workspace');

  try {
    await mkdir(workspaceDir, { recursive: true });

    const result = await initializeProjectMemory({
      cwd: tempDir,
      toolingRootDir: 'workspace',
      placementPattern: 'workspace-root',
      name: 'Workspace Root Project',
      mode: 'local-only',
      repos: [{ id: 'app', remote: 'https://github.com/example/app.git' }],
      bootstrap: {
        workflow: true,
        claude: true,
      },
    });

    const projectYaml = await readFile(path.join(workspaceDir, '.compass/project.yaml'), 'utf8');
    const context = await readFile(path.join(workspaceDir, '.compass/context.md'), 'utf8');
    const claude = await readFile(path.join(workspaceDir, 'CLAUDE.md'), 'utf8');

    assert.equal(result.rootDir, path.join(workspaceDir, '.compass'));
    assert.equal(result.contextFilePath, path.join(workspaceDir, '.compass/context.md'));
    assert.match(projectYaml, /placement_pattern: workspace-root/);
    assert.match(context, /\.compass\/project\.yaml/);
    assert.match(claude, /Read `\.compass\/context\.md` before doing substantive work/);
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});

test('runCli sync-agents creates and updates managed agent instruction files', async () => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'vibecompass-sync-agents-'));
  const rootDir = path.join(tempDir, '.compass');
  const stdout = [];
  const stderr = [];

  try {
    await initializeProjectMemory({
      cwd: tempDir,
      rootDir,
      name: 'Agent File Project',
      description: 'Keeps agent files generated from project memory.',
      mode: 'local-only',
      repos: [{ id: 'app', remote: 'https://github.com/example/app.git' }],
    });

    const dryRunExitCode = await runCli(
      ['sync-agents', '--root', '.compass', '--dry-run'],
      {
        stdout: {
          write(chunk) {
            stdout.push(chunk);
          },
        },
        stderr: {
          write() {},
        },
      },
      { cwd: tempDir },
    );

    await assert.rejects(() => access(path.join(tempDir, 'CLAUDE.md')));
    assert.equal(dryRunExitCode, 0);
    assert.match(stdout.join(''), /CLAUDE\.md: dry-run-create/);

    stdout.length = 0;
    const exitCode = await runCli(
      ['sync-agents', '--root', '.compass'],
      {
        stdout: {
          write(chunk) {
            stdout.push(chunk);
          },
        },
        stderr: {
          write() {},
        },
      },
      { cwd: tempDir },
    );

    const claude = await readFile(path.join(tempDir, 'CLAUDE.md'), 'utf8');
    const cursorRules = await readFile(path.join(tempDir, '.cursorrules'), 'utf8');
    const copilot = await readFile(path.join(tempDir, '.github/copilot-instructions.md'), 'utf8');

    assert.equal(exitCode, 0);
    assert.match(claude, /vibecompass:start - managed by VibeCompass/);
    assert.match(claude, /Agent File Project Claude Instructions/);
    assert.match(claude, /active builder sessions are named lanes/);
    assert.match(claude, /optional planning mode/);
    assert.match(claude, /vibecompass end-session/);
    assert.match(claude, /stale scratch files block `start-session`/);
    assert.match(cursorRules, /Agent File Project Cursor Rules/);
    assert.match(copilot, /Agent File Project Copilot Instructions/);

    await writeFile(
      path.join(tempDir, 'CLAUDE.md'),
      `User header\n\n${claude}\nUser footer\n`,
      'utf8',
    );

    await runCli(
      ['sync-agents', '--root', '.compass', '--format', 'claude_md'],
      {
        stdout: {
          write() {},
        },
        stderr: {
          write() {},
        },
      },
      { cwd: tempDir },
    );

    const updatedClaude = await readFile(path.join(tempDir, 'CLAUDE.md'), 'utf8');
    assert.match(updatedClaude, /^User header/);
    assert.match(updatedClaude, /User footer\s*$/);

    await writeFile(path.join(tempDir, 'AGENTS.md'), 'Hand-written agents file\n', 'utf8');
    stdout.length = 0;
    await runCli(
      ['sync-agents', '--root', '.compass', '--format', 'agents_md'],
      {
        stdout: {
          write(chunk) {
            stdout.push(chunk);
          },
        },
        stderr: {
          write(chunk) {
            stderr.push(chunk);
          },
        },
      },
      { cwd: tempDir },
    );

    assert.match(stderr.join(''), /AGENTS\.md: warning/);
    assert.equal(await readFile(path.join(tempDir, 'AGENTS.md'), 'utf8'), 'Hand-written agents file\n');
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});

test('runCli sync-agents reports disabled requested formats explicitly', async () => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'vibecompass-sync-disabled-'));
  const rootDir = path.join(tempDir, '.compass');
  const stdout = [];
  const stderr = [];

  try {
    await initializeProjectMemory({
      cwd: tempDir,
      rootDir,
      name: 'Disabled Agent File Project',
      mode: 'local-only',
      repos: [{ id: 'app', remote: 'https://github.com/example/app.git' }],
      metadata: {
        agent_files: {
          agents_md: false,
        },
      },
    });

    const exitCode = await runCli(
      ['sync-agents', '--root', '.compass', '--format', 'agents_md'],
      {
        stdout: {
          write(chunk) {
            stdout.push(chunk);
          },
        },
        stderr: {
          write(chunk) {
            stderr.push(chunk);
          },
        },
      },
      { cwd: tempDir },
    );

    assert.equal(exitCode, 0);
    assert.match(stdout.join(''), /Agent instruction files:/);
    assert.match(stderr.join(''), /AGENTS\.md: disabled/);
    assert.match(stderr.join(''), /Format "agents_md" is disabled/);
    await assert.rejects(() => access(path.join(tempDir, 'AGENTS.md')));
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});

test('runCli sync-agents validates format arguments', async () => {
  assert.throws(
    () => parseCliArgs(['sync-agents', '--format']),
    /requires a value/,
  );

  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'vibecompass-sync-validation-'));
  const rootDir = path.join(tempDir, '.compass');

  try {
    await initializeProjectMemory({
      cwd: tempDir,
      rootDir,
      name: 'Validation Agent File Project',
      mode: 'local-only',
      repos: [{ id: 'app', remote: 'https://github.com/example/app.git' }],
    });

    await assert.rejects(
      () =>
        runCli(
          ['sync-agents', '--root', '.compass', '--format', 'unknown'],
          {
            stdout: { write() {} },
            stderr: { write() {} },
          },
          { cwd: tempDir },
        ),
      /Unknown agent file format "unknown"/,
    );
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});

test('runCli docs-review performs mode-aware runtime preflight', async () => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'vibecompass-docs-review-'));
  const localOnlyRoot = path.join(tempDir, 'local-only');
  const localPrimaryRoot = path.join(tempDir, 'local-primary');
  const stdout = [];

  try {
    await initializeProjectMemory({
      cwd: tempDir,
      rootDir: localOnlyRoot,
      name: 'Local Only Review',
      mode: 'local-only',
      repos: [{ id: 'app', remote: 'https://github.com/example/app.git' }],
    });

    await runCli(
      ['docs-review', '--root', localOnlyRoot, '--llm', 'openai', '--model', 'gpt-5.5'],
      {
        stdout: { write() {} },
        stderr: { write() {} },
      },
      { cwd: tempDir, env: {} },
    );

    const localStdout = [];
    const localStderr = [];
    const localFetchCalls = [];
    await runCli(
      [
        'docs-review',
        '--root',
        localOnlyRoot,
        '--run-local',
        '--provider',
        'anthropic',
        '--llm',
        'claude',
        '--model',
        'claude-sonnet-4-6',
        '--max-tokens',
        '20000',
      ],
      {
        stdout: {
          write(chunk) {
            localStdout.push(chunk);
          },
        },
        stderr: {
          write(chunk) {
            localStderr.push(chunk);
          },
        },
      },
      {
        cwd: tempDir,
        env: { ANTHROPIC_API_KEY: 'anthropic_test' },
        async fetch(url, request) {
          localFetchCalls.push({ url, request });
          return {
            ok: true,
            status: 200,
            async json() {
              return {
                stop_reason: 'max_tokens',
                content: [
                  {
                    type: 'text',
                    text: [
                      'Generated review.',
                      '',
                      '```vibecompass-architecture-doc path=architecture/platform/docs-review/local-runtime.md',
                      '---',
                      'domain: Platform',
                      'feature: Docs Review',
                      'component: Local Runtime',
                      'status: In progress',
                      'repo: app',
                      '---',
                      '',
                      '## Description',
                      'Accepted local runtime docs.',
                      '',
                      '## Details',
                      'Generated review details.',
                      '',
                      '## Next steps',
                      '- Continue.',
                      '',
                      '## Involved files',
                      '- `app:src/docs-review.js`',
                      '```',
                    ].join('\n'),
                  },
                ],
              };
            },
          };
        },
      },
    );
    const localMarker = JSON.parse(await readFile(path.join(localOnlyRoot, 'state/docs-review.json'), 'utf8'));
    const localOutput = await readFile(path.join(localOnlyRoot, 'state/docs-review-output.md'), 'utf8');
    const localBody = JSON.parse(localFetchCalls[0].request.body);

    assert.equal(localFetchCalls.length, 1);
    assert.equal(localFetchCalls[0].url, 'https://api.anthropic.com/v1/messages');
    assert.equal(localFetchCalls[0].request.headers['x-api-key'], 'anthropic_test');
    assert.equal(localBody.model, 'claude-sonnet-4-6');
    assert.equal(localBody.max_tokens, 20000);
    assert.match(localBody.messages[0].content, /Confidence: high \| medium \| low/);
    assert.match(localStdout.join(''), /Docs-review: local-review-generated/);
    assert.match(localStdout.join(''), /Local review output:/);
    assert.match(localStderr.join(''), /stopped at max_tokens/);
    assert.equal(localMarker.status, 'local-review-generated');
    assert.equal(localMarker.local_review.provider, 'anthropic');
    assert.equal(localMarker.local_review.truncated, true);
    assert.match(localOutput, /Generated review/);
    assert.match(localMarker.runtime.provider, /local/);
    assert.equal(localMarker.runtime.local_provider, 'anthropic');

    const applyStdout = [];
    await runCli(
      ['docs-review', '--root', localOnlyRoot, '--apply-output'],
      {
        stdout: {
          write(chunk) {
            applyStdout.push(chunk);
          },
        },
        stderr: { write() {} },
      },
      { cwd: tempDir, env: {} },
    );
    const appliedDoc = await readFile(
      path.join(localOnlyRoot, 'architecture/platform/docs-review/local-runtime.md'),
      'utf8',
    );
    const appliedMarker = JSON.parse(await readFile(path.join(localOnlyRoot, 'state/docs-review.json'), 'utf8'));

    assert.match(applyStdout.join(''), /Applied architecture docs: 1/);
    assert.match(applyStdout.join(''), /architecture\/platform\/docs-review\/local-runtime\.md \(created\)/);
    assert.match(appliedDoc, /Accepted local runtime docs/);
    assert.equal(appliedMarker.status, 'completed');
    assert.deepEqual(appliedMarker.applied.architecture_docs, [
      { path: 'architecture/platform/docs-review/local-runtime.md', status: 'created' },
    ]);

    const overwriteStdout = [];
    await runCli(
      ['docs-review', '--root', localOnlyRoot, '--apply-output'],
      {
        stdout: {
          write(chunk) {
            overwriteStdout.push(chunk);
          },
        },
        stderr: { write() {} },
      },
      { cwd: tempDir, env: {} },
    );
    const overwrittenMarker = JSON.parse(await readFile(path.join(localOnlyRoot, 'state/docs-review.json'), 'utf8'));

    assert.match(overwriteStdout.join(''), /architecture\/platform\/docs-review\/local-runtime\.md \(overwritten\)/);
    assert.deepEqual(overwrittenMarker.applied.architecture_docs, [
      { path: 'architecture/platform/docs-review/local-runtime.md', status: 'overwritten' },
    ]);

    await initializeProjectMemory({
      cwd: tempDir,
      rootDir: localPrimaryRoot,
      name: 'Local Primary Review',
      mode: 'local-primary',
      repos: [{ id: 'app', remote: 'https://github.com/example/app.git' }],
      sync: {
        apiUrl: 'https://vibecompass.dev',
        projectId: 'vc_proj_review',
        credentialEnvVar: 'VIBECOMPASS_SYNC_TOKEN',
      },
    });

    const exitCode = await runCli(
      ['docs-review', '--root', localPrimaryRoot, '--guided'],
      {
        stdout: {
          write(chunk) {
            stdout.push(chunk);
          },
        },
        stderr: { write() {} },
      },
      {
        cwd: tempDir,
        env: {},
        prompt(spec) {
          if (spec.message === 'Preferred LLM for architecture review') {
            return 'codex';
          }

          if (spec.message === 'Model name to record') {
            return 'gpt-5.3-codex';
          }

          return spec.defaultValue ?? '';
        },
      },
    );
    const marker = JSON.parse(await readFile(path.join(localPrimaryRoot, 'state/docs-review.json'), 'utf8'));

    assert.equal(exitCode, 0);
    assert.match(stdout.join(''), /Docs-review: external-review-requested/);
    assert.match(stdout.join(''), /Runtime: hosted/);
    assert.match(stdout.join(''), /LLM: codex/);
    assert.match(stdout.join(''), /Model: gpt-5\.3-codex/);
    assert.match(stdout.join(''), /Architecture review prompt:/);
    assert.match(stdout.join(''), /# VibeCompass Docs Review Prompt v1/);
    assert.doesNotMatch(stdout.join(''), /Review created at:/);
    assert.match(stdout.join(''), /## Review metadata/);
    assert.match(stdout.join(''), /Review model\/version: gpt-5\.3-codex/);
    assert.match(stdout.join(''), /Do not delete `architecture\/overview\/project-shape\.md`/);
    assert.match(stdout.join(''), /body sections: `## Description`, `## Review metadata`, `## Details`, `## Next steps`, `## Involved files`/);
    assert.equal(marker.status, 'external-review-requested');
    assert.equal(marker.llm, 'codex');
    assert.equal(marker.model, 'gpt-5.3-codex');

    const hostedStdout = [];
    const submitFetchCalls = [];
    await runCli(
      ['docs-review', '--root', localPrimaryRoot, '--submit-hosted', '--llm', 'claude', '--model', 'claude-sonnet-4-6'],
      {
        stdout: {
          write(chunk) {
            hostedStdout.push(chunk);
          },
        },
        stderr: { write() {} },
      },
      {
        cwd: tempDir,
        env: { VIBECOMPASS_SYNC_TOKEN: 'vc_sync_test' },
        async fetch(url, request) {
          submitFetchCalls.push({ url, request });
          return {
            ok: true,
            status: 202,
            async json() {
              return { run_id: 'run_docs_review_123', status: 'accepted' };
            },
          };
        },
      },
    );
    const hostedMarker = JSON.parse(await readFile(path.join(localPrimaryRoot, 'state/docs-review.json'), 'utf8'));
    const hostedBody = JSON.parse(submitFetchCalls[0].request.body);

    assert.equal(submitFetchCalls.length, 1);
    assert.equal(submitFetchCalls[0].url, 'https://vibecompass.dev/api/sync/projects/vc_proj_review/docs-review');
    assert.equal(submitFetchCalls[0].request.headers.authorization, 'Bearer vc_sync_test');
    assert.equal(hostedBody.llm, 'claude');
    assert.equal(Object.hasOwn(hostedBody, 'project_memory_root'), false);
    assert.match(hostedBody.local_root_revision, /^loc_[a-f0-9]{24}$/);
    assert.equal(Object.hasOwn(hostedBody, 'baseline_remote_revision_id'), false);
    assert.match(hostedBody.evidence_scope.manifest_hash, /^sha256:[a-f0-9]{64}$/);
    assert.match(hostedBody.prompt, /# VibeCompass Docs Review Prompt v1/);
    assert.match(hostedBody.prompt, /Only include docs the user has accepted in fenced `vibecompass-architecture-doc` blocks/);
    assert.match(hostedStdout.join(''), /Docs-review: hosted-review-requested/);
    assert.match(hostedStdout.join(''), /Hosted run: run_docs_review_123/);
    assert.equal(hostedMarker.status, 'hosted-review-requested');
    assert.equal(hostedMarker.hosted.run_id, 'run_docs_review_123');
    assert.equal(hostedMarker.runtime.credential_env_var, 'VIBECOMPASS_SYNC_TOKEN');

    const pollStdout = [];
    const pollFetchCalls = [];
    await runCli(
      ['docs-review', '--root', localPrimaryRoot, '--poll-hosted'],
      {
        stdout: {
          write(chunk) {
            pollStdout.push(chunk);
          },
        },
        stderr: { write() {} },
      },
      {
        cwd: tempDir,
        env: { VIBECOMPASS_SYNC_TOKEN: 'vc_sync_test' },
        async fetch(url, request) {
          pollFetchCalls.push({ url, request });
          return {
            ok: true,
            status: 200,
            async json() {
              return {
                run_id: 'run_docs_review_123',
                status: 'completed',
                phase: null,
                prompt_version: 'VibeCompass Docs Review Prompt v1',
                parser_version: 'hosted-docs-review-parser-v1',
                proposal_ids: ['proposal_1'],
                warnings: [{ code: 'dropped_non_architecture_output', message: 'Dropped freeform text.' }],
              };
            },
          };
        },
      },
    );
    const polledMarker = JSON.parse(await readFile(path.join(localPrimaryRoot, 'state/docs-review.json'), 'utf8'));
    assert.equal(pollFetchCalls.length, 1);
    assert.equal(pollFetchCalls[0].url, 'https://vibecompass.dev/api/sync/projects/vc_proj_review/runs/run_docs_review_123');
    assert.equal(pollFetchCalls[0].request.headers.authorization, 'Bearer vc_sync_test');
    assert.match(pollStdout.join(''), /Docs-review: hosted-review-completed/);
    assert.match(pollStdout.join(''), /Hosted run: run_docs_review_123/);
    assert.equal(polledMarker.status, 'hosted-review-completed');
    assert.deepEqual(polledMarker.hosted.proposal_ids, ['proposal_1']);
    assert.equal(polledMarker.hosted.parser_version, 'hosted-docs-review-parser-v1');
    assert.equal(polledMarker.hosted.warnings[0].code, 'dropped_non_architecture_output');

    const failedPollStdout = [];
    await runCli(
      ['docs-review', '--root', localPrimaryRoot, '--poll-hosted'],
      {
        stdout: {
          write(chunk) {
            failedPollStdout.push(chunk);
          },
        },
        stderr: { write() {} },
      },
      {
        cwd: tempDir,
        env: { VIBECOMPASS_SYNC_TOKEN: 'vc_sync_test' },
        async fetch() {
          return {
            ok: true,
            status: 200,
            async json() {
              return {
                run_id: 'run_docs_review_123',
                status: 'failed',
                phase: null,
                error_code: 'no_baseline',
                error_message: 'No remote baseline revision was supplied.',
              };
            },
          };
        },
      },
    );
    const failedPollMarker = JSON.parse(await readFile(path.join(localPrimaryRoot, 'state/docs-review.json'), 'utf8'));
    assert.match(failedPollStdout.join(''), /Docs-review: hosted-review-failed/);
    assert.match(failedPollStdout.join(''), /Hosted docs-review run run_docs_review_123 is failed: No remote baseline revision was supplied\./);
    assert.equal(failedPollMarker.status, 'hosted-review-failed');
    assert.equal(failedPollMarker.hosted.error_code, 'no_baseline');
    assert.equal(failedPollMarker.hosted.error_message, 'No remote baseline revision was supplied.');

    const completeStdout = [];
    await runCli(
      ['docs-review', '--root', localPrimaryRoot, '--complete'],
      {
        stdout: {
          write(chunk) {
            completeStdout.push(chunk);
          },
        },
        stderr: { write() {} },
      },
      { cwd: tempDir, env: {} },
    );
    const completedMarker = JSON.parse(await readFile(path.join(localPrimaryRoot, 'state/docs-review.json'), 'utf8'));

    assert.match(completeStdout.join(''), /Docs-review: completed/);
    assert.doesNotMatch(completeStdout.join(''), /Architecture review prompt:/);
    assert.equal(completedMarker.status, 'completed');
    assert.equal(completedMarker.hosted.run_id, 'run_docs_review_123');
    assert.equal(completedMarker.llm, 'claude');
    assert.equal(completedMarker.model, 'claude-sonnet-4-6');
    assert.ok(completedMarker.completed_at);

    await assert.rejects(
      () =>
        runCli(
          ['docs-review', '--root', localPrimaryRoot, '--submit-hosted', '--run-local'],
          {
            stdout: { write() {} },
            stderr: { write() {} },
          },
          { cwd: tempDir, env: { ANTHROPIC_API_KEY: 'anthropic_test' } },
        ),
      /only one execution mode/,
    );
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});

test('runCli sync transport pushes, previews, exports, and applies proposals', async () => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'vibecompass-sync-flow-'));
  const rootDir = path.join(tempDir, '.compass');

  try {
    await initializeProjectMemory({
      rootDir,
      name: 'Sync Flow Project',
      slug: 'sync-flow-project',
      mode: 'local-primary',
      repos: [{ id: 'docs', remote: 'https://github.com/example/docs.git' }],
      sync: {
        apiUrl: 'https://vibecompass.dev',
        projectId: 'vc_proj_sync',
        credentialEnvVar: 'VIBECOMPASS_SYNC_TOKEN',
      },
      generatedAt: new Date('2026-05-09T10:00:00Z'),
    });

    const remoteRevisionId = '11111111-1111-4111-8111-111111111111';
    const proposalId = '22222222-2222-4222-8222-222222222222';
    const exportedText = [
      '---',
      'domain: Platform',
      'feature: Sync Flow',
      'component: Proposal Apply',
      'status: In progress',
      '---',
      '',
      '## Description',
      'Exported proposal doc.',
      '',
      '## Details',
      'Details.',
      '',
      '## Next steps',
      '- Push to confirm.',
      '',
      '## Involved files',
      '- `docs:architecture/platform/sync-flow/proposal-apply.md`',
      '',
    ].join('\n');
    const exportedHash = sha256Text(exportedText);
    const fetchCalls = [];

    async function fetch(url, request) {
      fetchCalls.push({ url, request });

      if (url.endsWith('/push')) {
        const body = JSON.parse(request.body);
        return {
          ok: true,
          status: 202,
          async json() {
            return {
              run_id: body.base_remote_revision_id ? 'run_push_confirm' : 'run_push_initial',
              status: 'completed',
              remote_revision_id: body.base_remote_revision_id
                ? '33333333-3333-4333-8333-333333333333'
                : remoteRevisionId,
              applied_proposal_ids: body.base_remote_revision_id ? [proposalId] : [],
              stale_proposal_ids: [],
            };
          },
        };
      }

      if (url.endsWith('/docs-review')) {
        return {
          ok: true,
          status: 202,
          async json() {
            return { run_id: 'run_docs_review_after_push', status: 'accepted' };
          },
        };
      }

      if (url.endsWith('/pull-preview')) {
        return {
          ok: true,
          status: 200,
          async json() {
            return {
              preview_token: 'preview_test_123',
              created_at: '2026-05-09T10:01:00.000Z',
              expires_at: '2026-05-09T10:31:00.000Z',
              base_remote_revision_id: remoteRevisionId,
              target_remote_revision_id: remoteRevisionId,
              authoritative_change_set_hash: `sha256:${'b'.repeat(64)}`,
              proposals: [
                {
                  proposal_id: proposalId,
                  status: 'open',
                  source: 'ai',
                  summary: 'Add sync flow proposal doc',
                  affected_paths: ['architecture/platform/sync-flow/proposal-apply.md'],
                },
              ],
              conflicts: [
                {
                  code: 'session_number_collision',
                  message: 'Local and hosted roots both use the same session number.',
                },
              ],
              warnings: [],
            };
          },
        };
      }

      if (url.endsWith('/pull-export')) {
        return {
          ok: true,
          status: 200,
          async json() {
            return {
              run_id: 'run_export_123',
              status: 'completed',
              preview_token: 'preview_test_123',
              target_remote_revision_id: remoteRevisionId,
              proposal_ids: [proposalId],
              operations: [
                {
                  proposal_id: proposalId,
                  position: 0,
                  op: 'write',
                  path: 'architecture/platform/sync-flow/proposal-apply.md',
                  kind: 'architecture',
                  before_content_hash: null,
                  after_content_hash: exportedHash,
                  content_hash: exportedHash,
                  raw_text: exportedText,
                },
              ],
            };
          },
        };
      }

      throw new Error(`Unexpected fetch ${url}`);
    }

    const pushStdout = [];
    await runCli(
      ['push', '--root', rootDir],
      { stdout: { write(chunk) { pushStdout.push(chunk); } }, stderr: { write() {} } },
      { cwd: tempDir, env: { VIBECOMPASS_SYNC_TOKEN: 'vc_sync_test' }, fetch },
    );
    const initialPushBody = JSON.parse(fetchCalls[0].request.body);
    assert.equal(fetchCalls[0].url, 'https://vibecompass.dev/api/sync/projects/vc_proj_sync/push');
    assert.equal(fetchCalls[0].request.headers.authorization, 'Bearer vc_sync_test');
    assert.equal(Object.hasOwn(initialPushBody, 'base_remote_revision_id'), false);
    assert.ok(initialPushBody.documents.some((document) => document.path === 'project.yaml' && document.raw_text.includes('Sync Flow Project')));
    assert.match(pushStdout.join(''), /Remote revision: 11111111-1111-4111-8111-111111111111/);

    await runCli(
      ['docs-review', '--root', rootDir, '--submit-hosted', '--llm', 'claude', '--model', 'claude-sonnet-4-6'],
      { stdout: { write() {} }, stderr: { write() {} } },
      { cwd: tempDir, env: { VIBECOMPASS_SYNC_TOKEN: 'vc_sync_test' }, fetch },
    );
    const docsReviewBody = JSON.parse(fetchCalls[1].request.body);
    assert.equal(fetchCalls[1].url, 'https://vibecompass.dev/api/sync/projects/vc_proj_sync/docs-review');
    assert.equal(docsReviewBody.baseline_remote_revision_id, remoteRevisionId);

    const previewStdout = [];
    await runCli(
      ['pull-preview', '--root', rootDir],
      { stdout: { write(chunk) { previewStdout.push(chunk); } }, stderr: { write() {} } },
      { cwd: tempDir, env: { VIBECOMPASS_SYNC_TOKEN: 'vc_sync_test' }, fetch },
    );
    const previewBody = JSON.parse(fetchCalls[2].request.body);
    assert.equal(previewBody.state_version, 1);
    assert.equal(previewBody.base_remote_revision_id, remoteRevisionId);
    assert.equal(previewBody.include_pending_proposals, true);
    assert.ok(previewBody.local_documents.some((document) => document.path === 'project.yaml'));
    assert.match(previewStdout.join(''), new RegExp(proposalId));
    assert.match(previewStdout.join(''), /session_number_collision/);

    const exportStdout = [];
    await runCli(
      ['pull-export', '--root', rootDir],
      { stdout: { write(chunk) { exportStdout.push(chunk); } }, stderr: { write() {} } },
      { cwd: tempDir, env: { VIBECOMPASS_SYNC_TOKEN: 'vc_sync_test' }, fetch },
    );
    const exportBody = JSON.parse(fetchCalls[3].request.body);
    assert.equal(exportBody.preview_token, 'preview_test_123');
    assert.deepEqual(exportBody.proposal_ids, [proposalId]);
    assert.match(exportStdout.join(''), /Operations: 1/);

    await runCli(
      ['apply-export', '--root', rootDir],
      { stdout: { write() {} }, stderr: { write() {} } },
      { cwd: tempDir, env: {} },
    );
    const appliedDoc = await readFile(
      path.join(rootDir, 'architecture/platform/sync-flow/proposal-apply.md'),
      'utf8',
    );
    assert.match(appliedDoc, /Exported proposal doc/);

    await runCli(
      ['push', '--root', rootDir],
      { stdout: { write() {} }, stderr: { write() {} } },
      { cwd: tempDir, env: { VIBECOMPASS_SYNC_TOKEN: 'vc_sync_test' }, fetch },
    );
    const confirmPushBody = JSON.parse(fetchCalls[4].request.body);
    assert.equal(confirmPushBody.base_remote_revision_id, remoteRevisionId);
    assert.ok(confirmPushBody.documents.some((document) => document.path === 'architecture/platform/sync-flow/proposal-apply.md'));
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});

test('initializeProjectMemory supports an existing docs-style root and preserves .gitignore content', async () => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'vibecompass-init-existing-'));

  try {
    await mkdir(path.join(tempDir, 'architecture/platform/project-memory'), { recursive: true });
    await mkdir(path.join(tempDir, 'decisions'), { recursive: true });
    await mkdir(path.join(tempDir, 'sessions'), { recursive: true });
    await writeFile(
      path.join(tempDir, 'architecture/platform/project-memory/backend.md'),
      [
        '---',
        'domain: Platform',
        'feature: Project Memory',
        'component: Backend',
        'status: In progress',
        'repo: docs',
        '---',
        '',
        '## Description',
        'Existing backend notes.',
        '',
        '## Details',
        'Details.',
        '',
        '## Next steps',
        '- Later.',
        '',
        '## Involved files',
        '- `docs:architecture/platform/project-memory/backend.md`',
        '',
      ].join('\n'),
      'utf8',
    );
    await writeFile(
      path.join(tempDir, 'decisions/cross-cutting.md'),
      [
        '### D-124 — Existing decision',
        '**Timestamp:** 2026-04-19 00:01 PDT',
        '**Decision:** Existing decision text.',
        '**Rationale:** Existing rationale.',
        '',
      ].join('\n'),
      'utf8',
    );
    await writeFile(
      path.join(tempDir, 'sessions/2026-04-19-1-existing.md'),
      [
        '# Session — 2026-04-19-1 — Existing',
        '',
        '## What we worked on',
        'Existing work.',
        '',
        '## Completed',
        '- Done.',
        '',
        '## Decisions made',
        '- D-124',
        '',
        '## Models used',
        '- Codex',
        '',
        '## Blockers / open questions',
        '- None.',
        '',
        '## Next session should start with',
        '- Continue.',
        '',
      ].join('\n'),
      'utf8',
    );
    await writeFile(path.join(tempDir, '.gitignore'), 'node_modules/\n', 'utf8');

    const result = await initializeProjectMemory({
      rootDir: tempDir,
      name: 'Dogfood',
      mode: 'local-primary',
      repos: [
        {
          id: 'docs',
          remote: 'https://github.com/example/docs.git',
          defaultBranch: 'main',
        },
      ],
      sync: {
        apiUrl: 'https://vibecompass.dev',
        projectId: 'vc_proj_dogfood',
        credentialEnvVar: 'VIBECOMPASS_SYNC_TOKEN',
      },
      generatedAt: new Date('2026-04-19T10:05:00Z'),
    });

    const gitignore = await readFile(path.join(tempDir, '.gitignore'), 'utf8');
    const projectYaml = await readFile(path.join(tempDir, 'project.yaml'), 'utf8');
    const liveScan = await scanProjectMemory(tempDir);

    assert.match(gitignore, /node_modules\//);
    assert.match(gitignore, /state\//);
    assert.match(projectYaml, /mode: local-primary/);
    assert.match(projectYaml, /credential_env_var: VIBECOMPASS_SYNC_TOKEN/);
    assert.equal(result.manifest.canonical.document_count, 4);
    assert.equal(liveScan.errors.length, 0);
    assert.equal(result.syncEnvVar, 'VIBECOMPASS_SYNC_TOKEN');
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});

test('runCli parses init arguments and creates the root', async () => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'vibecompass-cli-'));
  const rootDir = path.join(tempDir, '.compass');
  const stdout = [];
  const stderr = [];

  try {
    const parsed = parseCliArgs([
      'init',
      '--root',
      rootDir,
      '--name',
      'CLI Project',
      '--mode',
      'local-only',
      '--repo',
      'docs=https://github.com/example/docs.git',
      '--repo-branch',
      'docs=main',
      '--with-workflow',
      '--with-claude',
      '--close-session-git-publish',
      '--close-session-git-remote',
      'upstream',
    ]);

    assert.equal(parsed.command, 'init');
    assert.equal(parsed.options.repos[0].defaultBranch, 'main');
    assert.equal(parsed.options.bootstrap.workflow, true);
    assert.equal(parsed.options.bootstrap.claude, true);
    assert.equal(parsed.options.closeSessionGitPublish, true);
    assert.equal(parsed.options.closeSessionGitRemote, 'upstream');

    const exitCode = await runCli(
      [
        'init',
        '--root',
        rootDir,
        '--name',
        'CLI Project',
        '--mode',
        'local-only',
        '--repo',
        'docs=https://github.com/example/docs.git',
        '--repo-branch',
        'docs=main',
        '--with-workflow',
        '--with-claude',
        '--close-session-git-publish',
        '--close-session-git-remote',
        'upstream',
      ],
      {
        stdout: {
          write(chunk) {
            stdout.push(chunk);
          },
        },
        stderr: {
          write(chunk) {
            stderr.push(chunk);
          },
        },
      },
      {
        cwd: tempDir,
      },
    );

    assert.equal(exitCode, 0);
    assert.equal(stderr.length, 0);
    assert.ok(stdout.join('').includes('Initialized VibeCompass project memory'));
    assert.ok(stdout.join('').includes('Generated'));
    assert.ok(stdout.join('').includes('context.md'));
    assert.ok(stdout.join('').includes(path.join(tempDir, 'CLAUDE.md')));
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});

test('runCli can chain init directly into the first builder session', async () => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'vibecompass-cli-init-session-'));
  const stdout = [];
  const stderr = [];

  try {
    const exitCode = await runCli(
      [
        'init',
        '--name',
        'CLI Session Bootstrap',
        '--mode',
        'local-only',
        '--repo',
        'docs=https://github.com/example/docs.git',
        '--start-session',
        '--session-id',
        'bootstrap-session',
        '--session-working-on',
        'Kick off the first builder session from init.',
      ],
      {
        stdout: {
          write(chunk) {
            stdout.push(chunk);
          },
        },
        stderr: {
          write(chunk) {
            stderr.push(chunk);
          },
        },
      },
      {
        cwd: tempDir,
      },
    );

    const claude = await readFile(path.join(tempDir, 'CLAUDE.md'), 'utf8');
    const wip = await readFile(path.join(tempDir, '.compass/sessions/active/bootstrap-session/wip.md'), 'utf8');
    const handoff = await readFile(path.join(tempDir, '.compass/sessions/active/bootstrap-session/handoff.md'), 'utf8');
    const activeIndex = await readFile(path.join(tempDir, '.compass/sessions/active/index.yaml'), 'utf8');

    assert.equal(exitCode, 0);
    assert.match(stderr.join(''), /CLAUDE\.md: warning/);
    assert.ok(stdout.join('').includes('Generated'));
    assert.ok(stdout.join('').includes('Started session'));
    assert.match(claude, /Working on: Kick off the first builder session from init\./);
    assert.match(wip, /Kick off the first builder session from init\./);
    assert.match(handoff, /Kick off the first builder session from init\./);
    assert.match(activeIndex, /current: bootstrap-session/);
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});

test('runCli supports guided init with placement recommendation and first-session bootstrap', async () => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'vibecompass-cli-guided-'));
  const stdout = [];
  const stderr = [];
  const prompts = [];
  const answers = new Map([
    ['Project name', 'Guided Project'],
    ['Project mode', 'local-only'],
    ['How many repos belong to this logical project?', '1'],
    ['Repo 1 id', 'app'],
    ['Repo 1 remote', 'https://github.com/example/app.git'],
    ['Repo 1 default branch', 'main'],
    ['Use primary-repo?', ''],
    ['Directory of the designated primary repo', '.'],
    ['Scaffold workflow files (context.md plus guide READMEs)?', ''],
    ['Create a starter CLAUDE.md if missing?', ''],
    ['Create a starter AGENTS.md if missing?', 'no'],
    ['Open the first builder session immediately after init?', 'yes'],
    ['What are you working on?', 'Bootstrap the guided init flow.'],
    ['Session lane id', 'guided-bootstrap'],
    ['Should close-session include a Git publish step?', 'yes'],
    ['Git remote for the close-session publish step', ''],
  ]);

  try {
    const exitCode = await runCli(
      ['init', '--guided'],
      {
        stdout: {
          write(chunk) {
            stdout.push(chunk);
          },
        },
        stderr: {
          write(chunk) {
            stderr.push(chunk);
          },
        },
      },
      {
        cwd: tempDir,
        async prompt(spec) {
          prompts.push(spec.message);
          if (!answers.has(spec.message)) {
            throw new Error(`Unexpected guided prompt: ${spec.message}`);
          }

          return answers.get(spec.message);
        },
      },
    );

    const projectYaml = await readFile(path.join(tempDir, '.compass/project.yaml'), 'utf8');
    const claude = await readFile(path.join(tempDir, 'CLAUDE.md'), 'utf8');
    const wip = await readFile(path.join(tempDir, '.compass/sessions/active/guided-bootstrap/wip.md'), 'utf8');

    assert.equal(exitCode, 0);
    assert.match(stderr.join(''), /CLAUDE\.md: warning/);
    await access(path.join(tempDir, 'AGENTS.md'));
    assert.deepEqual(prompts, [
      'Project name',
      'Project mode',
      'How many repos belong to this logical project?',
      'Repo 1 id',
      'Repo 1 remote',
      'Repo 1 default branch',
      'Use primary-repo?',
      'Directory of the designated primary repo',
      'Scaffold workflow files (context.md plus guide READMEs)?',
      'Create a starter CLAUDE.md if missing?',
      'Create a starter AGENTS.md if missing?',
      'Open the first builder session immediately after init?',
      'What are you working on?',
      'Session lane id',
      'Should close-session include a Git publish step?',
      'Git remote for the close-session publish step',
    ]);
    assert.ok(stdout.join('').includes('Placement: primary-repo'));
    assert.ok(stdout.join('').includes('Started session'));
    assert.match(projectYaml, /placement_pattern: primary-repo/);
    assert.match(projectYaml, /default_branch: main/);
    assert.match(projectYaml, /git_publish: true/);
    assert.match(projectYaml, /git_remote: origin/);
    assert.match(claude, /Working on: Bootstrap the guided init flow\./);
    assert.match(wip, /Bootstrap the guided init flow\./);
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});

test('runCli guided init defaults a single primary repo to the matching child directory', async () => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'vibecompass-cli-guided-child-repo-'));
  const stdout = [];
  const stderr = [];
  const prompts = [];
  const answers = new Map([
    ['Project name', 'Child Repo Project'],
    ['Project mode', 'local-only'],
    ['How many repos belong to this logical project?', '1'],
    ['Repo 1 id', 'app'],
    ['Repo 1 remote', 'https://github.com/example/app.git'],
    ['Repo 1 default branch', ''],
    ['Use primary-repo?', ''],
    ['Directory of the designated primary repo', ''],
    ['Scaffold workflow files (context.md plus guide READMEs)?', 'no'],
    ['Open the first builder session immediately after init?', 'no'],
  ]);

  try {
    await mkdir(path.join(tempDir, 'app'), { recursive: true });

    const exitCode = await runCli(
      ['init', '--guided'],
      {
        stdout: {
          write(chunk) {
            stdout.push(chunk);
          },
        },
        stderr: {
          write(chunk) {
            stderr.push(chunk);
          },
        },
      },
      {
        cwd: tempDir,
        async prompt(spec) {
          prompts.push(spec.message);
          if (!answers.has(spec.message)) {
            throw new Error(`Unexpected guided prompt: ${spec.message}`);
          }

          return answers.get(spec.message);
        },
      },
    );

    const projectYaml = await readFile(path.join(tempDir, 'app/.compass/project.yaml'), 'utf8');

    await assert.rejects(() => access(path.join(tempDir, '.compass/project.yaml')));

    assert.equal(exitCode, 0);
    assert.equal(stderr.length, 0);
    assert.deepEqual(prompts, [
      'Project name',
      'Project mode',
      'How many repos belong to this logical project?',
      'Repo 1 id',
      'Repo 1 remote',
      'Repo 1 default branch',
      'Use primary-repo?',
      'Directory of the designated primary repo',
      'Scaffold workflow files (context.md plus guide READMEs)?',
      'Open the first builder session immediately after init?',
    ]);
    assert.ok(stdout.join('').includes(path.join(tempDir, 'app/.compass')));
    assert.match(projectYaml, /placement_pattern: primary-repo/);
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});

test('initializeProjectMemory regenerates context.md on rerun with force and workflow scaffolding', async () => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'vibecompass-init-context-rewrite-'));
  const rootDir = path.join(tempDir, '.compass');

  try {
    await initializeProjectMemory({
      cwd: tempDir,
      rootDir,
      name: 'First Name',
      mode: 'local-only',
      repos: [{ id: 'docs', remote: 'https://github.com/example/docs.git' }],
      bootstrap: {
        workflow: true,
      },
    });

    const contextPath = path.join(rootDir, 'context.md');
    await writeFile(contextPath, '# User edited context\n', 'utf8');

    await initializeProjectMemory({
      cwd: tempDir,
      rootDir,
      force: true,
      name: 'Second Name',
      mode: 'local-only',
      repos: [{ id: 'docs', remote: 'https://github.com/example/docs.git' }],
      bootstrap: {
        workflow: true,
      },
    });

    const context = await readFile(contextPath, 'utf8');
    assert.match(context, /Project Context — Second Name/);
    assert.doesNotMatch(context, /User edited context/);
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});

test('initializeProjectMemory never overwrites an existing tool bootstrap file', async () => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'vibecompass-init-existing-tool-'));
  const rootDir = path.join(tempDir, '.compass');

  try {
    await writeFile(path.join(tempDir, 'AGENTS.md'), '# Existing AGENTS\n', 'utf8');

    const result = await initializeProjectMemory({
      cwd: tempDir,
      rootDir,
      name: 'Existing Tool Project',
      mode: 'local-only',
      repos: [{ id: 'docs', remote: 'https://github.com/example/docs.git' }],
      bootstrap: {
        agents: true,
      },
    });

    const agents = await readFile(path.join(tempDir, 'AGENTS.md'), 'utf8');
    assert.equal(agents, '# Existing AGENTS\n');
    assert.ok(result.scaffoldSkippedFiles.includes(path.join(tempDir, 'AGENTS.md')));
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});

test('initializeProjectMemory rejects sync configuration outside local-primary mode', async () => {
  await assert.rejects(
    () =>
      initializeProjectMemory({
        rootDir: '/tmp/vibecompass-invalid-sync',
        name: 'Invalid Sync Project',
        mode: 'local-only',
        repos: [{ id: 'docs', remote: 'https://github.com/example/docs.git' }],
        sync: {
          apiUrl: 'https://vibecompass.dev',
          projectId: 'vc_proj_invalid',
          credentialEnvVar: 'VIBECOMPASS_SYNC_TOKEN',
        },
      }),
    /sync configuration is only supported when mode is local-primary/i,
  );
});

test('docs-review applies hosted decision artifacts append-only with next D-number', async () => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'vibecompass-decision-artifact-'));
  const rootDir = path.join(tempDir, '.compass');

  try {
    await mkdir(path.join(rootDir, 'decisions'), { recursive: true });
    await mkdir(path.join(rootDir, 'state'), { recursive: true });
    await writeFile(
      path.join(rootDir, 'decisions/cross-cutting.md'),
      [
        '# Cross-cutting decisions',
        '',
        '### D-124 — Existing decision',
        '',
        '**Timestamp:** 2026-04-19 00:01 UTC-07:00',
        '**Decision:** Existing decision text.',
        '**Rationale:** Existing rationale.',
        '',
      ].join('\n'),
      'utf8',
    );
    await writeFile(
      path.join(rootDir, 'state/docs-review.json'),
      `${JSON.stringify({
        status: 'hosted-review-completed',
        hosted: {
          run_id: 'run_docs_review_123',
          artifacts: [
            {
              artifact_id: 'artifact_decision_1',
              artifact_type: 'decision_recommendation',
              title: 'Decision artifacts append locally',
              summary: 'Decision recommendations append locally instead of overwriting decision files.',
              target_path: 'decisions/cross-cutting.md',
              content: {
                target_path: 'decisions/cross-cutting.md',
                title: 'Decision artifacts append locally',
                decision: 'Decision recommendations append locally instead of overwriting decision files.',
                rationale: 'Decision logs are append-only and D-numbers must be allocated from current local state.',
              },
            },
          ],
        },
      }, null, 2)}\n`,
      'utf8',
    );

    const stdout = [];
    const stderr = [];
    await runCli(
      [
        'docs-review',
        '--root',
        rootDir,
        '--apply-decision-artifact',
        '--artifact',
        'artifact_decision_1',
      ],
      {
        stdout: { write(chunk) { stdout.push(chunk); } },
        stderr: { write(chunk) { stderr.push(chunk); } },
      },
      { cwd: tempDir, env: {} },
    );

    const decisions = await readFile(path.join(rootDir, 'decisions/cross-cutting.md'), 'utf8');
    const marker = JSON.parse(await readFile(path.join(rootDir, 'state/docs-review.json'), 'utf8'));

    assert.match(stdout.join(''), /Applied decision artifact: artifact_decision_1/);
    assert.match(stderr.join(''), /decisions\/INDEX\.md was not refreshed/);
    assert.match(decisions, /### D-125 — Decision artifacts append locally/);
    assert.doesNotMatch(decisions, /\*\*Source:\*\*/);
    await assert.rejects(
      () => access(path.join(rootDir, 'decisions/INDEX.md')),
      /ENOENT/,
    );
    assert.equal(marker.applied_decision_artifact.decision_id, 125);
    assert.equal(marker.applied_decision_artifact.refreshed_index, false);
    assert.equal(marker.hosted.artifacts[0].local_status, 'applied');
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});

test('docs-review rejects decision artifacts without rationale', async () => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'vibecompass-decision-artifact-rationale-'));
  const rootDir = path.join(tempDir, '.compass');

  try {
    await mkdir(path.join(rootDir, 'decisions'), { recursive: true });
    await mkdir(path.join(rootDir, 'state'), { recursive: true });
    await writeFile(
      path.join(rootDir, 'decisions/cross-cutting.md'),
      [
        '# Cross-cutting decisions',
        '',
        '### D-124 — Existing decision',
        '',
        '**Timestamp:** 2026-04-19 00:01 PDT',
        '**Decision:** Existing decision text.',
        '**Rationale:** Existing rationale.',
        '',
      ].join('\n'),
      'utf8',
    );
    await writeFile(
      path.join(rootDir, 'state/docs-review.json'),
      `${JSON.stringify({
        status: 'hosted-review-completed',
        hosted: {
          run_id: 'run_docs_review_123',
          artifacts: [
            {
              artifact_id: 'artifact_decision_missing_rationale',
              artifact_type: 'decision_recommendation',
              title: 'Missing rationale',
              summary: 'This should not be accepted without rationale.',
              target_path: 'decisions/cross-cutting.md',
              content: {
                target_path: 'decisions/cross-cutting.md',
                title: 'Missing rationale',
                decision: 'This should not be accepted without rationale.',
              },
            },
          ],
        },
      }, null, 2)}\n`,
      'utf8',
    );

    await assert.rejects(
      () =>
        runCli(
          [
            'docs-review',
            '--root',
            rootDir,
            '--apply-decision-artifact',
            '--artifact',
            'artifact_decision_missing_rationale',
          ],
          { stdout: { write() {} }, stderr: { write() {} } },
          { cwd: tempDir, env: {} },
        ),
      /must include a non-empty rationale/,
    );
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});

test('docs-review can refresh the flat decision index when explicitly requested', async () => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'vibecompass-decision-artifact-index-'));
  const rootDir = path.join(tempDir, '.compass');

  try {
    await mkdir(path.join(rootDir, 'decisions'), { recursive: true });
    await mkdir(path.join(rootDir, 'state'), { recursive: true });
    await writeFile(
      path.join(rootDir, 'decisions/cross-cutting.md'),
      [
        '# Cross-cutting decisions',
        '',
        '### D-124 — Existing decision',
        '',
        '**Timestamp:** 2026-04-19 00:01 PDT',
        '**Decision:** Existing decision text.',
        '**Rationale:** Existing rationale.',
        '',
      ].join('\n'),
      'utf8',
    );
    await writeFile(
      path.join(rootDir, 'state/docs-review.json'),
      `${JSON.stringify({
        status: 'hosted-review-completed',
        hosted: {
          run_id: 'run_docs_review_123',
          artifacts: [
            {
              artifact_id: 'artifact_decision_refresh_index',
              artifact_type: 'decision_recommendation',
              title: 'Refresh index explicitly',
              summary: 'The flat decision index refresh is explicit.',
              target_path: 'decisions/cross-cutting.md',
              content: {
                target_path: 'decisions/cross-cutting.md',
                title: 'Refresh index explicitly',
                decision: 'The flat decision index refresh is explicit.',
                rationale: 'Some roots intentionally use the package-generated flat decision index.',
              },
            },
          ],
        },
      }, null, 2)}\n`,
      'utf8',
    );

    await runCli(
      [
        'docs-review',
        '--root',
        rootDir,
        '--apply-decision-artifact',
        '--artifact',
        'artifact_decision_refresh_index',
        '--refresh-index',
      ],
      { stdout: { write() {} }, stderr: { write() {} } },
      { cwd: tempDir, env: {} },
    );

    const index = await readFile(path.join(rootDir, 'decisions/INDEX.md'), 'utf8');
    const marker = JSON.parse(await readFile(path.join(rootDir, 'state/docs-review.json'), 'utf8'));

    assert.match(index, /D-125 \| Refresh index explicitly/);
    assert.equal(marker.applied_decision_artifact.refreshed_index, true);
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});

test('isDirectExecution resolves symlinked bin entry paths', async () => {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'vibecompass-bin-'));
  const cliPath = fileURLToPath(new URL('../cli.js', import.meta.url));
  const symlinkPath = path.join(tempDir, 'vibecompass');

  try {
    await writeFile(symlinkPath, '', 'utf8');
    await rm(symlinkPath, { force: true });
    await import('node:fs/promises').then(({ symlink }) => symlink(cliPath, symlinkPath));

    assert.equal(isDirectExecution(symlinkPath, new URL('../cli.js', import.meta.url).href), true);

    const result = spawnSync(process.execPath, [symlinkPath, '--help'], {
      encoding: 'utf8',
    });

    assert.equal(result.status, 0);
    assert.match(result.stdout, /Usage:/);
    assert.equal(result.stderr, '');
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
});
