import { PACKAGE_VERSION } from '../version.js';

export const WORKFLOW_REGISTRY = [
  {
    id: 'session-lifecycle',
    title: 'Session lifecycle',
    detailPath: 'context.md',
    summary: 'Builder/reviewer lane lifecycle, handoffs, planning mode, and close-out.',
    promptCommands: [
      { trigger: 'start session', summary: 'builder role trigger' },
      { trigger: 'join as reviewer', summary: 'reviewer role trigger' },
      { trigger: 'planning mode', summary: 'optional prompt-level mode for scoping work before implementation' },
      { trigger: 'review handoff', summary: 'reviewer reads the selected lane handoff and appends findings; with multiple active lanes name the lane explicitly: `review handoff <lane-id>`' },
      { trigger: 'address review', summary: 'builder critically resolves reviewer feedback from the selected lane scratch files' },
      { trigger: 'docs update', summary: 'builder runs a targeted session-delta documentation maintenance plan with `vibecompass docs-update --session <lane-id>`' },
      { trigger: 'close session', summary: 'builder runs the close-out checklist and ends with `vibecompass close-session --session <lane-id>` plus required document-maintenance checkpoint statuses; `end session` and `vibecompass end-session` are accepted aliases' },
    ],
  },
  {
    id: 'docs-review',
    title: 'Docs review',
    detailPath: 'workflows/docs-review.md',
    summary: 'Generate evidence-backed architecture docs from the user\'s preferred AI session.',
    promptCommands: [
      { trigger: 'docs review', summary: 'agent-led architecture documentation review using the preferred LLM prompt box' },
    ],
    generatedFileKind: 'workflow-docs-review',
    renderFile: renderDocsReviewWorkflow,
  },
];

export function getPromptCommands() {
  return WORKFLOW_REGISTRY.flatMap((workflow) =>
    workflow.promptCommands.map((command) => ({
      ...command,
      workflowId: workflow.id,
      workflowTitle: workflow.title,
      detailPath: workflow.detailPath,
    })),
  );
}

export function getWorkflowConflictScanPatterns() {
  const patterns = new Set([
    'session',
    'handoff',
    'decisions',
    'wip.md',
    'builder',
    'reviewer',
  ]);

  for (const command of getPromptCommands()) {
    const normalizedTrigger = command.trigger.toLowerCase();
    patterns.add(normalizedTrigger);
    patterns.add(slugifyPromptTrigger(normalizedTrigger));
  }

  return Array.from(patterns);
}

export function getGeneratedWorkflowFiles(options = {}) {
  const rootRelativePath = options.rootRelativePath ?? '.';
  return WORKFLOW_REGISTRY
    .filter((workflow) => typeof workflow.renderFile === 'function')
    .map((workflow) => ({
      kind: workflow.generatedFileKind,
      relativePath: workflow.detailPath,
      content: workflow.renderFile({
        rootRelativePath,
        workflow,
      }),
    }));
}

export function renderPromptCommandLines(options = {}) {
  const rootRelativePath = options.rootRelativePath ?? '.';
  return getPromptCommands().map((command) => {
    const detailPath = command.detailPath
      ? ` Read \`${joinRootRelative(rootRelativePath, command.detailPath)}\` for the full workflow.`
      : '';
    return `- \`${command.trigger}\` — ${command.summary}.${detailPath}`;
  });
}

function renderDocsReviewWorkflow(options = {}) {
  const rootRelativePath = options.rootRelativePath ?? '.';
  const projectYamlPath = joinRootRelative(rootRelativePath, 'project.yaml');
  const contextPath = joinRootRelative(rootRelativePath, 'context.md');
  const architecturePath = joinRootRelative(rootRelativePath, 'architecture/');
  const decisionsPath = joinRootRelative(rootRelativePath, 'decisions/');
  const sessionsPath = joinRootRelative(rootRelativePath, 'sessions/');
  const outputPath = joinRootRelative(rootRelativePath, 'state/docs-review-output.md');
  const applyCommand = `vibecompass docs-review --root ${rootRelativePath} --apply-output --output ${outputPath}`;
  const npxApplyCommand = `npx -y @vibecompass/vibecompass@${PACKAGE_VERSION} docs-review --root ${rootRelativePath} --apply-output --output ${outputPath}`;

  return `# VibeCompass Workflow — docs review

Generated by VibeCompass. This file is a package-owned workflow guide and may be refreshed by \`vibecompass refresh-workflow --apply\`.

## Prompt trigger

When the user says \`docs review\`, run this workflow inside the current Claude Code, Codex, Cursor, or Copilot session. The npm package owns state markers and apply mechanics; the AI session owns repository inspection and writing accepted docs-review output.

## Goal

Turn starter project memory into evidence-backed architecture docs under \`architecture/<domain>/<feature>/<component>.md\`, a projected coverage plan, a journey-aware project map, and optional accepted decision recommendations.

The first pass is breadth-first: establish an honest project denominator, compact baseline docs, and explicit deferred or missing areas before spending tokens on deep dives. Focused deepening happens after that baseline, either because the user chooses a feature/system or because an implementation session needs better docs for a specific area.

## Steps

1. Read \`${projectYamlPath}\`, \`${contextPath}\`, existing \`${architecturePath}\`, \`${decisionsPath}\`, and finalized \`${sessionsPath}\` notes.
2. Inspect the declared source repos in stages:
   - inventory paths, manifests, configs, route/job/test directories, and existing architecture frontmatter first
   - identify project topology before choosing taxonomy: single-repo/monolith, multi-repo, multi-surface, package/CLI, workers/services, mobile app, or mixed
   - build a subsystem-level completeness inventory of apps/repos, routes/screens, APIs, tables/storage, jobs/cron/tasks, auth/session flows, external integrations, runtime surfaces, and product features
   - distinguish product features from participating surfaces such as web, mobile, backend/API, data, jobs, integrations, and deployment/runtime
   - produce a coverage plan before reading broad source bodies
   - classify each planned area as \`baseline\` breadth or \`deepening\` follow-up scope
   - read targeted source files only when the coverage plan needs evidence
3. Run \`vibecompass docs-review --guided --llm <tool-name> --model <model-name>\` to record the review marker and print the canonical docs-review contract. Use the current AI tool name and model when known.
4. Present the evidence inventory, completeness inventory with accepted/deferred/missing accounting, topology, chosen taxonomy axis, prior-doc reuse/update/split/merge/defer/replace classifications, coverage plan, backbone outputs (core feature inventory, user journey map, project systems map, coverage/quality summary), proposed architecture docs, blindspots, token-budget risks, quality report, and any decision candidates before generating accepted output. At this gate, ask whether to apply the compact baseline now, adjust the plan, or spend a follow-up pass deepening specific high-risk areas. If you stop here for user approval, state clearly that no architecture docs have been applied yet and do not label proposed areas as accepted.
5. Draft only output the user accepts. After approval, the accepted plan must be fenced as \`vibecompass-coverage-plan version=1\` and should preserve each area's \`run_scope\` as \`baseline\` or \`deepening\`. Accepted architecture docs must be fenced as \`vibecompass-architecture-doc path=architecture/domain/feature/component.md\` blocks and must include required frontmatter: \`domain\`, \`feature\`, \`component\`, and \`status\`. Feature docs may include compact prose-only surface matrices; surface/platform ownership docs stay under the existing \`architecture/platform/<surface>/<component>.md\` shape rather than a new top-level systems tree. The accepted \`architecture/overview/project-shape.md\` doc should include compact backbone sections and exactly one \`vibecompass-project-map version=1\` JSON block with journey-facing features, entry points, evidence-backed relationships, and minimal optional derived \`systems[]\` metadata. Accepted local decisions may be fenced as \`vibecompass-decision-recommendation target=decisions/domain.md\` blocks without D-numbers.
6. Keep each generated architecture doc focused and retrieval-oriented. Soft budget: under 12000 bytes per doc unless the extra detail is necessary and called out in review metadata or retrieval guidance. Write every doc as a current-state contract (D-292): updates rewrite the affected sections in place or create a new focused doc — never append dated session/audit sections. Keep the durable plan and rollout state in the doc; work/ship chronology belongs in session notes, and decision entries record accepted choices (D-293).
7. Write the accepted fenced blocks verbatim to \`${outputPath}\`.
8. Run \`${applyCommand}\` to validate and apply the accepted blocks. If \`vibecompass\` is not installed on PATH, run \`${npxApplyCommand}\` instead. Only report docs-review as applied after this command succeeds. If accepted docs were written manually outside the output file, run \`vibecompass docs-review --root ${rootRelativePath} --complete\` after confirming the marker should be completed.
9. Run \`vibecompass status\` to confirm the docs-review marker is complete and not drifted. Report the applied architecture paths, coverage projection, baseline/deepening split, decision recommendations, parser warnings such as oversized docs or missing review metadata, and any blindspots or deepening candidates documented in the accepted docs-review output.

## Rebuild option

If the user explicitly wants to rerun docs-review for a focused architecture-doc scope, preview the scope first with \`vibecompass docs-review --rebuild --path architecture/<scope>\`. Only apply cleanup after the user accepts the preview; use \`vibecompass docs-review --rebuild --apply --stale-policy archive --path architecture/<scope>\` when the user explicitly wants selected stale docs archived before the next review. Rebuild archives selected \`architecture/**/*.md\` docs under \`state/docs-review-archive/\`; it does not mutate decisions, sessions, project.yaml, workflow files, agent instruction files, \`architecture/README.md\`, or \`architecture/overview/project-shape.md\`. Rebuild is not permission to cold-regenerate taxonomy: the next docs-review coverage plan must anchor to the prior tree and explain reuse/update/split/merge/defer/replace actions before prose generation.

## Rules

- Do not duplicate the full canonical review prompt in this file. The package command prints that contract from its current implementation.
- Follow the canonical review prompt for evidence, blindspot, and decision-recommendation constraints.
- Treat the package-owned prompt as the source of truth. Tool-specific skills may wrap this workflow, but should not define a divergent docs-review protocol.
- Do not edit generated agent files directly. Update VibeCompass project memory or rerun package commands instead.
`;
}

function slugifyPromptTrigger(trigger) {
  return trigger.trim().replace(/\s+/g, '-');
}

function joinRootRelative(rootRelativePath, relativePath) {
  if (!rootRelativePath || rootRelativePath === '.') {
    return relativePath;
  }

  return `${rootRelativePath.replace(/\/$/, '')}/${relativePath}`;
}
