export const WORKFLOW_REGISTRY = [
  {
    id: 'session-lifecycle',
    title: 'Session lifecycle',
    detailPath: 'context.md',
    summary: 'Builder/reviewer lane lifecycle, handoffs, planning mode, and close-out.',
    promptCommands: [
      { trigger: 'start session', summary: 'builder role trigger' },
      { trigger: 'join as reviewer', summary: 'reviewer role trigger' },
      { trigger: 'planning mode', summary: 'optional prompt-level mode for scoping work before implementation' },
      { trigger: 'review handoff', summary: 'reviewer reads the selected lane handoff and appends findings' },
      { trigger: 'address review', summary: 'builder processes reviewer feedback from the selected lane scratch files' },
      { trigger: 'close session', summary: 'builder runs the close-out checklist and ends with `vibecompass close-session --session <lane-id>`; `end session` and `vibecompass end-session` are accepted aliases' },
    ],
  },
  {
    id: 'docs-review',
    title: 'Docs review',
    detailPath: 'workflows/docs-review.md',
    summary: 'Generate evidence-backed architecture docs from the user\'s preferred AI session.',
    promptCommands: [
      { trigger: 'docs review', summary: 'agent-led architecture documentation review using the preferred LLM prompt box' },
    ],
    generatedFileKind: 'workflow-docs-review',
    renderFile: renderDocsReviewWorkflow,
  },
];

export function getPromptCommands() {
  return WORKFLOW_REGISTRY.flatMap((workflow) =>
    workflow.promptCommands.map((command) => ({
      ...command,
      workflowId: workflow.id,
      workflowTitle: workflow.title,
      detailPath: workflow.detailPath,
    })),
  );
}

export function getWorkflowConflictScanPatterns() {
  const patterns = new Set([
    'session',
    'handoff',
    'decisions',
    'wip.md',
    'builder',
    'reviewer',
  ]);

  for (const command of getPromptCommands()) {
    const normalizedTrigger = command.trigger.toLowerCase();
    patterns.add(normalizedTrigger);
    patterns.add(slugifyPromptTrigger(normalizedTrigger));
  }

  return Array.from(patterns);
}

export function getGeneratedWorkflowFiles(options = {}) {
  const rootRelativePath = options.rootRelativePath ?? '.';
  return WORKFLOW_REGISTRY
    .filter((workflow) => typeof workflow.renderFile === 'function')
    .map((workflow) => ({
      kind: workflow.generatedFileKind,
      relativePath: workflow.detailPath,
      content: workflow.renderFile({
        rootRelativePath,
        workflow,
      }),
    }));
}

export function renderPromptCommandLines(options = {}) {
  const rootRelativePath = options.rootRelativePath ?? '.';
  return getPromptCommands().map((command) => {
    const detailPath = command.detailPath
      ? ` Read \`${joinRootRelative(rootRelativePath, command.detailPath)}\` for the full workflow.`
      : '';
    return `- \`${command.trigger}\` — ${command.summary}.${detailPath}`;
  });
}

function renderDocsReviewWorkflow(options = {}) {
  const rootRelativePath = options.rootRelativePath ?? '.';
  const projectYamlPath = joinRootRelative(rootRelativePath, 'project.yaml');
  const contextPath = joinRootRelative(rootRelativePath, 'context.md');
  const architecturePath = joinRootRelative(rootRelativePath, 'architecture/');
  const decisionsPath = joinRootRelative(rootRelativePath, 'decisions/');
  const sessionsPath = joinRootRelative(rootRelativePath, 'sessions/');
  const outputPath = joinRootRelative(rootRelativePath, 'state/docs-review-output.md');

  return `# VibeCompass Workflow — docs review

Generated by VibeCompass. This file is a package-owned workflow guide and may be refreshed by \`vibecompass refresh-workflow --apply\`.

## Prompt trigger

When the user says \`docs review\`, run this workflow inside the current Claude Code, Codex, Cursor, or Copilot session. The npm package owns state markers and apply mechanics; the AI session owns repository inspection and writing accepted architecture docs.

## Goal

Turn starter project memory into evidence-backed architecture docs under \`architecture/<domain>/<feature>/<component>.md\`.

## Steps

1. Read \`${projectYamlPath}\`, \`${contextPath}\`, existing \`${architecturePath}\`, \`${decisionsPath}\`, and finalized \`${sessionsPath}\` notes.
2. Inspect the declared source repos before making implementation claims. Cite concrete files as \`repo:path\` evidence in generated docs.
3. Run \`vibecompass docs-review --guided --llm <tool-name> --model <model-name>\` to record the review marker and print the canonical docs-review contract. Use the current AI tool name and model when known.
4. Draft only architecture docs the user accepts. Accepted docs must be fenced exactly as \`vibecompass-architecture-doc path=architecture/domain/feature/component.md\` blocks and must include required frontmatter: \`domain\`, \`feature\`, \`component\`, and \`status\`.
5. Write the accepted fenced blocks to \`${outputPath}\`.
6. Run \`vibecompass docs-review --apply-output\` to validate and apply the accepted blocks. If accepted docs were written manually outside the output file, run \`vibecompass docs-review --complete\` after confirming the marker should be completed.
7. Run \`vibecompass status\` to confirm the docs-review marker is complete. Report the applied architecture paths from the \`--apply-output\` result and any blindspots documented in the accepted docs-review output.

## Rules

- Do not duplicate the full canonical review prompt in this file. The package command prints that contract from its current implementation.
- Follow the canonical review prompt for evidence, blindspot, and decision-recommendation constraints.
- Do not edit generated agent files directly. Update VibeCompass project memory or rerun package commands instead.
`;
}

function slugifyPromptTrigger(trigger) {
  return trigger.trim().replace(/\s+/g, '-');
}

function joinRootRelative(rootRelativePath, relativePath) {
  if (!rootRelativePath || rootRelativePath === '.') {
    return relativePath;
  }

  return `${rootRelativePath.replace(/\/$/, '')}/${relativePath}`;
}
